# Generated by Django 5.2.14 on 2026-08-28 08:44

import django.db.models.deletion
import utils.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('children', '0004_child_graduated_circle_graduated'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeePayment',
            fields=[
                ('id', models.CharField(default=utils.models.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('month', models.CharField(help_text='Month the payment covers, formatted as YYYY-MM (e.g. 2026-08).', max_length=7)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='children.child')),
            ],
            options={
                'db_table': 'fee_payments',
                'ordering': ['-month'],
            },
        ),
    ]
