# Generated by Django 5.2.14 on 2026-06-24 04:01

import django.db.models.deletion
import utils.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('children', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.CharField(default=utils.models.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('circles', models.ManyToManyField(blank=True, related_name='announcements', to='children.circle')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'announcements',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='AnnouncementAck',
            fields=[
                ('id', models.CharField(default=utils.models.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acks', to='announcements.announcement')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_acks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'announcement_acks',
                'unique_together': {('announcement', 'parent')},
            },
        ),
    ]
