# Generated by Django 5.2.14 on 2026-08-30 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_announcement_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcementphoto',
            name='announcement',
        ),
        migrations.DeleteModel(
            name='AnnouncementAck',
        ),
        migrations.DeleteModel(
            name='AnnouncementPhoto',
        ),
    ]
