# Generated by Django 5.2.14 on 2026-06-24 03:23

import utils.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.CharField(default=utils.models.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'children',
                'db_table': 'children',
            },
        ),
        migrations.CreateModel(
            name='Circle',
            fields=[
                ('id', models.CharField(default=utils.models.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('family', 'Family'), ('classroom', 'Classroom')], max_length=10)),
                ('children', models.ManyToManyField(blank=True, related_name='circles', to='children.child')),
                ('members', models.ManyToManyField(blank=True, related_name='circles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'circles',
            },
        ),
    ]
