# Generated by Django 5.2.14 on 2026-08-09 02:24

import django.db.models.deletion
import utils.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Django can't AlterField a plain M2M into a through= M2M, so drop the
        # auto join table, create the explicit through model, then re-add the
        # relation pointing at it. (Drops any existing circle memberships.)
        migrations.RemoveField(
            model_name='circle',
            name='members',
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.CharField(default=utils.models.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('relationship', models.CharField(blank=True, choices=[('mother', 'Mother'), ('father', 'Father'), ('guardian', 'Guardian'), ('other', 'Other')], max_length=20)),
                ('circle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_records', to='children.circle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'members',
                'unique_together': {('user', 'circle')},
            },
        ),
        migrations.AddField(
            model_name='circle',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='circles', through='children.Member', to=settings.AUTH_USER_MODEL),
        ),
    ]
