# Generated by Django 5.2.14 on 2026-08-09 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0002_member_alter_circle_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='relationship',
            field=models.CharField(blank=True, choices=[('mother', 'Mother'), ('father', 'Father'), ('guardian', 'Guardian'), ('teacher', 'Teacher'), ('other', 'Other')], max_length=20),
        ),
    ]
