# Generated by Django 5.2.14 on 2026-08-09 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0003_alter_member_relationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='graduated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='circle',
            name='graduated',
            field=models.BooleanField(default=False),
        ),
    ]
