# Generated by Django 5.2.14 on 2026-08-29 00:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0002_lessoncompletion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='send_hour',
            field=models.PositiveSmallIntegerField(default=14, help_text='Hour of day (0-23, Asia/Dili) at which due lessons are sent.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)]),
        ),
    ]
