# Generated by Django 5.2.14 on 2026-08-18 22:38

import django.db.models.deletion
import utils.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundMessage',
            fields=[
                ('id', models.CharField(default=utils.models.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('from_phone', models.CharField(max_length=20)),
                ('wa_message_id', models.CharField(max_length=128, unique=True)),
                ('message_type', models.CharField(blank=True, max_length=20)),
                ('text', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inbound_messages',
                'ordering': ['-created'],
            },
        ),
    ]
