# Generated by Django 5.2.14 on 2026-08-29 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('messaging', '0004_seed_periodic_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagelog',
            name='source_id',
            field=models.CharField(blank=True, db_index=True, max_length=26, null=True),
        ),
        migrations.AddField(
            model_name='messagelog',
            name='source_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
    ]
