# Generated by Django 5.2.14 on 2026-08-30 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0005_messagelog_source_id_messagelog_source_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='digestqueue',
            name='message_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='digest_items', to='messaging.messagelog'),
        ),
    ]
