# Generated by Django 5.2.14 on 2026-08-30 02:37

import django.db.models.deletion
import photos.models
import utils.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.CharField(default=utils.models.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('owner_id', models.CharField(db_index=True, max_length=26)),
                ('image', models.ImageField(upload_to=photos.models.photo_upload_path)),
                ('owner_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'photos',
                'ordering': ['created'],
            },
        ),
    ]
