# Generated by Django 5.2.14 on 2026-06-24 03:23

import django.db.models.deletion
import utils.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('children', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.CharField(default=utils.models.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('photo', models.ImageField(blank=True, upload_to='updates/photos/')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='children.child')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'updates',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='UrgentAlert',
            fields=[
                ('id', models.CharField(default=utils.models.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urgent_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'urgent_alerts',
                'ordering': ['-created'],
            },
        ),
    ]
