# Generated by Django 5.2.14 on 2026-08-30 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='update',
            name='photo',
        ),
    ]
